# Generated by Django 3.2 on 2022-12-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название Фирмы')),
                ('address_firm', models.CharField(max_length=50, verbose_name='Адрес Фирмы')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.category')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.firm')),
            ],
        ),
    ]
