# Generated by Django 3.2 on 2022-12-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firm',
            old_name='address_firm',
            new_name='address',
        ),
    ]
